In [110]:
from sklearn.linear_model import LogisticRegression
from sklearn import datasets
import numpy as np

### С регуляризацией

In [149]:
X, y = datasets.make_classification(n_features=5, n_samples=10000, n_redundant=0, n_informative=3)
print(np.unique(y)) # бинарная классификация


[0 1]


In [150]:
mdl = LogisticRegression(penalty='l2', multi_class='ovr', solver='newton-cg')

In [151]:
mdl.fit(X, y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='ovr', n_jobs=None, penalty='l2',
                   random_state=None, solver='newton-cg', tol=0.0001, verbose=0,
                   warm_start=False)

In [152]:
mdl.coef_ 

array([[-2.00910374,  0.20522439, -0.04847334, -0.02528456,  0.21879702]])

In [153]:
mdl = LogisticRegression(penalty='l2', multi_class='multinomial', solver='newton-cg')

In [154]:
mdl.fit(X, y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='multinomial', n_jobs=None, penalty='l2',
                   random_state=None, solver='newton-cg', tol=0.0001, verbose=0,
                   warm_start=False)

In [155]:
2 * mdl.coef_ 

array([[-2.01084219,  0.20541774, -0.04852482, -0.02532784,  0.2194082 ]])

Как видим, веса отличаются уже во 2 знаке после запятой.

### Теперь посмотрим без регуляризации.

In [156]:
mdl = LogisticRegression(penalty='none', multi_class='ovr', solver='newton-cg', max_iter=500)
mdl.fit(X, y)
mdl.coef_ 

array([[-2.01258661,  0.20561167, -0.04857653, -0.02537126,  0.22002145]])

In [157]:
mdl = LogisticRegression(penalty='none', multi_class='multinomial', solver='newton-cg', max_iter=500)
mdl.fit(X, y)
2 * mdl.coef_ 

array([[-2.01258664,  0.20561167, -0.04857651, -0.02537128,  0.22002147]])

Как видим, здесь точное совпадение (небольшое отличие лишь в 8 знаке после запятой, которое можно отнести к погрешности).